Repository Hanghae99-FinalProject-Buycation/BE-Buycation, pull requests merged in 2023-02, with the labels that each got.

#111 ♻️ Refactor: 스케쥴러 수정
  Buycation/src/main/java/com/example/buycation/posting/repository/PostingRepository.java
  Buycation/src/main/java/com/example/buycation/posting/service/PostingService.java
  Buycation/src/main/java/com/example/buycation/scheduler/Scheduler.java
  Buycation/src/main/java/com/example/buycation/talk/repository/ChatRoomRepository.java
  Buycation/src/main/java/com/example/buycation/talk/repository/TalkRepository.java
Labels: refactor

#113 ♻️ Refactor : 서비스간의 의존성 제거, 이벤트 리스너 도입
  Buycation/src/main/java/com/example/buycation/alarm/AlarmListner.java
  Buycation/src/main/java/com/example/buycation/alarm/dto/RealtimeAlarmDto.java
  Buycation/src/main/java/com/example/buycation/alarm/entity/AlarmType.java
  Buycation/src/main/java/com/example/buycation/alarm/mapper/AlarmMapper.java
  Buycation/src/main/java/com/example/buycation/alarm/repository/EmitterRepository.java
  Buycation/src/main/java/com/example/buycation/alarm/service/AlarmService.java
  Buycation/src/main/java/com/example/buycation/comment/service/CommentService.java
  Buycation/src/main/java/com/example/buycation/participant/service/ParticipantService.java
  Buycation/src/main/java/com/example/buycation/posting/service/PostingService.java
  Buycation/src/main/java/com/example/buycation/scheduler/Scheduler.java
  Buycation/src/main/java/com/example/buycation/talk/repository/TalkRepository.java
Labels: refactor

#115 ♻️ Refactor: 마이페이지 조회 정렬값 수정
  Buycation/src/main/java/com/example/buycation/members/profile/service/ProfileService.java
  Buycation/src/main/java/com/example/buycation/posting/repository/PostingRepository.java
  Buycation/src/main/java/com/example/buycation/scheduler/Scheduler.java
Labels: refactor

#116 🐛 Fix : 알림 내용 빠지던 현상 수정
  Buycation/src/main/java/com/example/buycation/comment/service/CommentService.java
  Buycation/src/main/java/com/example/buycation/participant/service/ParticipantService.java
  Buycation/src/main/java/com/example/buycation/posting/service/PostingService.java
  Buycation/src/main/java/com/example/buycation/scheduler/Scheduler.java
Labels: bug

#119 ♻️ Refactor: 게시글 상세 좌표값 추가
  Buycation/src/main/java/com/example/buycation/posting/dto/PostingResponseDto.java
  Buycation/src/main/java/com/example/buycation/posting/mapper/PostingMapper.java
Labels: refactor

#117 🐛 Fix : 게시글 수정 에러 처리
  Buycation/src/main/java/com/example/buycation/posting/service/PostingService.java
  Buycation/src/main/java/com/example/buycation/talk/dto/TalkResponseDto.java
Labels: bug

#120 ♻️ Refactor : 알림 메세지 내용 변경
  Buycation/src/main/java/com/example/buycation/alarm/entity/AlarmType.java
  Buycation/src/main/java/com/example/buycation/participant/service/ParticipantService.java
Labels: refactor

#122 🐛 Fix : alarm read시 갯수 +1 삭제
  Buycation/src/main/java/com/example/buycation/alarm/service/AlarmService.java
Labels: bug

#126 ♻️ Refactor: 스케쥴러 수정
  Buycation/src/main/java/com/example/buycation/posting/repository/PostingRepository.java
  Buycation/src/main/java/com/example/buycation/scheduler/Scheduler.java
Labels: refactor

#124 ♻️ Refactor: 레디스 추가 및 이메일 인증 수정
  Buycation/src/main/java/com/example/buycation/common/exception/ErrorCode.java
  Buycation/src/main/java/com/example/buycation/mail/entity/EmailCheck.java
  Buycation/src/main/java/com/example/buycation/mail/mapper/EmailCheckMapper.java
  Buycation/src/main/java/com/example/buycation/mail/repository/EmailCheckRepository.java
  Buycation/src/main/java/com/example/buycation/mail/service/EmailService.java
  Buycation/src/main/java/com/example/buycation/members/member/controller/MemberController.java
  Buycation/src/main/java/com/example/buycation/members/member/service/MemberService.java
Labels: feature
