Repository Hanghae99-FinalProject-Buycation/BE-Buycation, pull requests merged in 2023-01, with the labels that each got.

#2 ✨ Feat: 백앤드 기본 틀 생성
  Buycation/.gitignore
  Buycation/build.gradle
  Buycation/settings.gradle
  Buycation/src/main/java/com/example/buycation/BuycationApplication.java
  Buycation/src/main/java/com/example/buycation/comment/entity/Comment.java
  Buycation/src/main/java/com/example/buycation/common/MessageCode.java
  Buycation/src/main/java/com/example/buycation/common/ResponseMessage.java
  Buycation/src/main/java/com/example/buycation/common/TimeStamped.java
  Buycation/src/main/java/com/example/buycation/common/exception/CustomException.java
  Buycation/src/main/java/com/example/buycation/common/exception/ErrorCode.java
  Buycation/src/main/java/com/example/buycation/common/exception/GlobalExceptionHandler.java
  Buycation/src/main/java/com/example/buycation/members/member/entity/Member.java
  Buycation/src/main/java/com/example/buycation/members/profile/entity/Review.java
  Buycation/src/main/java/com/example/buycation/participant/entity/Application.java
  Buycation/src/main/java/com/example/buycation/participant/entity/Participant.java
  Buycation/src/main/java/com/example/buycation/posting/entity/Category.java
  Buycation/src/main/java/com/example/buycation/posting/entity/Posting.java
  Buycation/src/main/resources/application.properties
  Buycation/src/test/java/com/example/buycation/BuycationApplicationTests.java
Labels: feature

#6 ✨ Feat: 성공메세지 추가
  Buycation/src/main/java/com/example/buycation/common/MessageCode.java
Labels: feature

#11 ✨ Feat: 댓글 작성 API
  Buycation/build.gradle
  Buycation/src/main/java/com/example/buycation/comment/controller/CommentController.java
  Buycation/src/main/java/com/example/buycation/comment/dto/CommentRequestDto.java
  Buycation/src/main/java/com/example/buycation/comment/entity/Comment.java
  Buycation/src/main/java/com/example/buycation/comment/mapper/CommentMapper.java
  Buycation/src/main/java/com/example/buycation/comment/repository/CommentRepository.java
  Buycation/src/main/java/com/example/buycation/comment/service/CommentService.java
  Buycation/src/main/java/com/example/buycation/common/MessageCode.java
  Buycation/src/main/java/com/example/buycation/common/exception/ErrorCode.java
  Buycation/src/main/java/com/example/buycation/common/exception/GlobalExceptionHandler.java
  Buycation/src/main/java/com/example/buycation/members/member/entity/Member.java
  Buycation/src/main/java/com/example/buycation/posting/entity/Posting.java
  Buycation/src/main/java/com/example/buycation/posting/repository/PostingRepository.java
Labels: feature

#15 ✨ Feat: 댓글 삭제 API
  Buycation/src/main/java/com/example/buycation/comment/controller/CommentController.java
  Buycation/src/main/java/com/example/buycation/comment/service/CommentService.java
Labels: feature

#17 ✨ Feat: 게시글 작성 및 상세조회 API
  Buycation/src/main/java/com/example/buycation/comment/dto/CommentResponseDto.java
  Buycation/src/main/java/com/example/buycation/comment/mapper/CommentMapper.java
  Buycation/src/main/java/com/example/buycation/comment/repository/CommentRepository.java
  Buycation/src/main/java/com/example/buycation/comment/service/CommentService.java
  Buycation/src/main/java/com/example/buycation/members/member/entity/Member.java
  Buycation/src/main/java/com/example/buycation/posting/controller/PostingController.java
  Buycation/src/main/java/com/example/buycation/posting/dto/PostingRequestDto.java
  Buycation/src/main/java/com/example/buycation/posting/dto/PostingResponseDto.java
  Buycation/src/main/java/com/example/buycation/posting/entity/Posting.java
  Buycation/src/main/java/com/example/buycation/posting/mapper/PostingMapper.java
  Buycation/src/main/java/com/example/buycation/posting/service/PostingService.java
  Buycation/src/main/java/com/example/buycation/security/config/WebSecurityConfig.java
Labels: feature

#20 ✨ Feat: 게시글 참가신청 및 지원자 조회 API
  Buycation/src/main/java/com/example/buycation/comment/entity/Comment.java
  Buycation/src/main/java/com/example/buycation/common/MessageCode.java
  Buycation/src/main/java/com/example/buycation/common/exception/ErrorCode.java
  Buycation/src/main/java/com/example/buycation/participant/controller/ParticipantController.java
  Buycation/src/main/java/com/example/buycation/participant/dto/ApplicationResponseDto.java
  Buycation/src/main/java/com/example/buycation/participant/entity/Application.java
  Buycation/src/main/java/com/example/buycation/participant/mapper/ApplicationMapper.java
  Buycation/src/main/java/com/example/buycation/participant/repository/ApplicationRepository.java
  Buycation/src/main/java/com/example/buycation/participant/repository/ParticipantRepository.java
  Buycation/src/main/java/com/example/buycation/participant/service/ParticipantService.java
  Buycation/src/main/java/com/example/buycation/posting/entity/Posting.java
  Buycation/src/main/java/com/example/buycation/posting/service/PostingService.java
Labels: feature

#22 ✨ Feat: 신청자 수락 및 거절 API
  Buycation/src/main/java/com/example/buycation/common/MessageCode.java
  Buycation/src/main/java/com/example/buycation/common/exception/ErrorCode.java
  Buycation/src/main/java/com/example/buycation/participant/controller/ParticipantController.java
  Buycation/src/main/java/com/example/buycation/participant/entity/Participant.java
  Buycation/src/main/java/com/example/buycation/participant/mapper/ApplicationMapper.java
  Buycation/src/main/java/com/example/buycation/participant/repository/ParticipantRepository.java
  Buycation/src/main/java/com/example/buycation/participant/service/ParticipantService.java
  Buycation/src/main/java/com/example/buycation/posting/service/PostingService.java
Labels: feature

#24 ✨ Feat: 게시글 참가 취소 API
  Buycation/src/main/java/com/example/buycation/common/exception/ErrorCode.java
  Buycation/src/main/java/com/example/buycation/participant/controller/ParticipantController.java
  Buycation/src/main/java/com/example/buycation/participant/service/ParticipantService.java
Labels: feature

#26 ✨ Feat: 게시글 완료, 수정 API
  Buycation/src/main/java/com/example/buycation/common/MessageCode.java
  Buycation/src/main/java/com/example/buycation/common/exception/ErrorCode.java
  Buycation/src/main/java/com/example/buycation/participant/service/ParticipantService.java
  Buycation/src/main/java/com/example/buycation/posting/controller/PostingController.java
  Buycation/src/main/java/com/example/buycation/posting/entity/Posting.java
  Buycation/src/main/java/com/example/buycation/posting/mapper/PostingMapper.java
  Buycation/src/main/java/com/example/buycation/posting/service/PostingService.java
Labels: feature

#28 ✨ Feat: 게시글 삭제 API
  Buycation/src/main/java/com/example/buycation/comment/mapper/CommentMapper.java
  Buycation/src/main/java/com/example/buycation/comment/repository/CommentRepository.java
  Buycation/src/main/java/com/example/buycation/participant/repository/ApplicationRepository.java
  Buycation/src/main/java/com/example/buycation/participant/repository/ParticipantRepository.java
  Buycation/src/main/java/com/example/buycation/posting/controller/PostingController.java
  Buycation/src/main/java/com/example/buycation/posting/mapper/PostingMapper.java
  Buycation/src/main/java/com/example/buycation/posting/service/PostingService.java
Labels: feature

#30 ✨ Feat: 메인 전체 조회 API
  Buycation/src/main/java/com/example/buycation/common/exception/ErrorCode.java
  Buycation/src/main/java/com/example/buycation/participant/service/ParticipantService.java
  Buycation/src/main/java/com/example/buycation/posting/controller/PostingController.java
  Buycation/src/main/java/com/example/buycation/posting/dto/MainPostingResponseDto.java
  Buycation/src/main/java/com/example/buycation/posting/dto/PostingResponseDto.java
  Buycation/src/main/java/com/example/buycation/posting/entity/Category.java
  Buycation/src/main/java/com/example/buycation/posting/mapper/PostingMapper.java
  Buycation/src/main/java/com/example/buycation/posting/service/PostingService.java
Labels: feature

#32 ✨ Feat: 닉네임 중복 api
  Buycation/src/main/java/com/example/buycation/members/member/controller/MemberController.java
  Buycation/src/main/java/com/example/buycation/members/member/service/MemberService.java
Labels: feature

#34 ✨ Feat: 리뷰 등록 API
  Buycation/src/main/java/com/example/buycation/comment/service/CommentService.java
  Buycation/src/main/java/com/example/buycation/common/exception/ErrorCode.java
  Buycation/src/main/java/com/example/buycation/members/member/entity/Member.java
  Buycation/src/main/java/com/example/buycation/members/profile/controller/ProfileController.java
  Buycation/src/main/java/com/example/buycation/members/profile/dto/ReviewRequestDto.java
  Buycation/src/main/java/com/example/buycation/members/profile/entity/Review.java
  Buycation/src/main/java/com/example/buycation/members/profile/mapper/ReviewMapper.java
  Buycation/src/main/java/com/example/buycation/members/profile/repository/ReviewRepository.java
  Buycation/src/main/java/com/example/buycation/members/profile/service/ProfileService.java
  Buycation/src/main/java/com/example/buycation/participant/service/ParticipantService.java
  Buycation/src/main/java/com/example/buycation/posting/service/PostingService.java
Labels: feature

#37 ✨ Feat: 자신의 게시글, 참여한 게시글, 멤버 리뷰 목록 조회 API
  Buycation/src/main/java/com/example/buycation/common/exception/ErrorCode.java
  Buycation/src/main/java/com/example/buycation/members/profile/controller/ProfileController.java
  Buycation/src/main/java/com/example/buycation/members/profile/dto/MemberReviewResponseDto.java
  Buycation/src/main/java/com/example/buycation/members/profile/mapper/ReviewMapper.java
  Buycation/src/main/java/com/example/buycation/members/profile/service/ProfileService.java
  Buycation/src/main/java/com/example/buycation/participant/repository/ParticipantRepository.java
  Buycation/src/main/java/com/example/buycation/posting/repository/PostingRepository.java
Labels: feature

#40 ✨ Feat: 전체 검색 조회 API
  Buycation/src/main/java/com/example/buycation/posting/controller/PostingController.java
  Buycation/src/main/java/com/example/buycation/posting/dto/MainPostingResponseDto.java
  Buycation/src/main/java/com/example/buycation/posting/entity/Posting.java
  Buycation/src/main/java/com/example/buycation/posting/mapper/PostingMapper.java
  Buycation/src/main/java/com/example/buycation/posting/repository/PostingRepository.java
  Buycation/src/main/java/com/example/buycation/posting/service/PostingService.java
Labels: feature

#41 ♻️ Refactor: grable ignore 해제
  Buycation/gradlew
Labels: refactor

#42 ♻️ Refactor: ignore 수정
  Buycation/gradle/wrapper/gradle-wrapper.jar
  Buycation/gradle/wrapper/gradle-wrapper.properties
  Buycation/gradlew.bat
Labels: refactor

#44 ♻️ Refactor: 좌표값 추가, 검색 조회 조건 강화
  Buycation/src/main/java/com/example/buycation/common/exception/ErrorCode.java
  Buycation/src/main/java/com/example/buycation/posting/controller/PostingController.java
  Buycation/src/main/java/com/example/buycation/posting/dto/MainPostingResponseDto.java
  Buycation/src/main/java/com/example/buycation/posting/dto/PostingRequestDto.java
  Buycation/src/main/java/com/example/buycation/posting/entity/Posting.java
  Buycation/src/main/java/com/example/buycation/posting/mapper/PostingMapper.java
  Buycation/src/main/java/com/example/buycation/posting/repository/PostingRepository.java
  Buycation/src/main/java/com/example/buycation/posting/service/PostingService.java
Labels: refactor

#45 ✨ Feat: start.sh, stop.sh, appspec.yml
  Buycation/ start.sh
  Buycation/appspec.yml
  Buycation/stop.sh
Labels: feature

#46 ♻️ Refactor: start.sh와 stop.sh를 script 패키지 안에 넣음
  Buycation/scripts/start.sh
  Buycation/scripts/stop.sh
Labels: refactor

#47 ✨ Feat: 이메일 인증 API
  Buycation/.gitignore
  Buycation/build.gradle
  Buycation/src/main/java/com/example/buycation/common/exception/ErrorCode.java
  Buycation/src/main/java/com/example/buycation/mail/config/EmailConfig.java
  Buycation/src/main/java/com/example/buycation/mail/controller/EmailController.java
  Buycation/src/main/java/com/example/buycation/mail/service/EmailService.java
  Buycation/src/main/resources/application.properties
Labels: feature

#49 ♻️ Refactor: member 패키지관련 파일 refactoring
  Buycation/build.gradle
  Buycation/src/main/java/com/example/buycation/common/exception/ErrorCode.java
  Buycation/src/main/java/com/example/buycation/common/exception/GlobalExceptionHandler.java
  Buycation/src/main/java/com/example/buycation/members/mapper/MemberMapper.java
  Buycation/src/main/java/com/example/buycation/members/member/controller/MemberController.java
  Buycation/src/main/java/com/example/buycation/members/member/dto/SignupRequestDto.java
  Buycation/src/main/java/com/example/buycation/members/member/service/MemberService.java
Labels: refactor

#51 ♻️ Refactor: 포스팅에 addressDetail 추가
  Buycation/src/main/java/com/example/buycation/members/member/mapper/MemberMapper.java
  Buycation/src/main/java/com/example/buycation/members/member/service/MemberService.java
  Buycation/src/main/java/com/example/buycation/posting/dto/PostingRequestDto.java
  Buycation/src/main/java/com/example/buycation/posting/dto/PostingResponseDto.java
  Buycation/src/main/java/com/example/buycation/posting/entity/Posting.java
  Buycation/src/main/java/com/example/buycation/posting/mapper/PostingMapper.java
  Buycation/src/main/java/com/example/buycation/posting/repository/PostingRepository.java
  Buycation/src/main/java/com/example/buycation/posting/service/PostingService.java
Labels: refactor

#53 ✨ Feat: 회원 조회, 수정 API
  Buycation/src/main/java/com/example/buycation/common/MessageCode.java
  Buycation/src/main/java/com/example/buycation/common/exception/ErrorCode.java
  Buycation/src/main/java/com/example/buycation/members/member/controller/MemberController.java
  Buycation/src/main/java/com/example/buycation/members/member/dto/LoginResponseDto.java
  Buycation/src/main/java/com/example/buycation/members/member/dto/MemberResponseDto.java
  Buycation/src/main/java/com/example/buycation/members/member/dto/UpdateMemberRequestDto.java
  Buycation/src/main/java/com/example/buycation/members/member/entity/Member.java
  Buycation/src/main/java/com/example/buycation/members/member/mapper/MemberMapper.java
  Buycation/src/main/java/com/example/buycation/members/member/service/MemberService.java
  Buycation/src/main/java/com/example/buycation/members/profile/dto/ReviewResponseDto.java
  Buycation/src/main/java/com/example/buycation/members/profile/mapper/ReviewMapper.java
  Buycation/src/main/java/com/example/buycation/members/profile/repository/ReviewRepository.java
  Buycation/src/main/java/com/example/buycation/members/profile/service/ProfileService.java
Labels: feature, refactor

#54 ♻️ Refactor: mysql dependency 추가
  Buycation/build.gradle
Labels: refactor

#55 ♻️ Refactor: config toh2Console 부분 제거
  Buycation/src/main/java/com/example/buycation/security/config/WebSecurityConfig.java
Labels: refactor

#56 ♻️ Refactor: .requestMatchers(PathRequest.toH2Console()) 추가
  Buycation/src/main/java/com/example/buycation/security/config/WebSecurityConfig.java
Labels: refactor

#57 ♻️ Refactor: h2 디펜던시 추가
  Buycation/build.gradle
Labels: refactor

#59 ♻️ Refactor: 회원 정보 수정 조건 추가
  Buycation/src/main/java/com/example/buycation/members/member/dto/MemberResponseDto.java
  Buycation/src/main/java/com/example/buycation/members/member/entity/Member.java
  Buycation/src/main/java/com/example/buycation/members/member/mapper/MemberMapper.java
  Buycation/src/main/java/com/example/buycation/members/member/service/MemberService.java
Labels: refactor

#61 ✨/♻️ Feat and Refactor:
  Buycation/src/main/java/com/example/buycation/BuycationApplication.java
  Buycation/src/main/java/com/example/buycation/comment/repository/CommentRepository.java
  Buycation/src/main/java/com/example/buycation/comment/service/CommentService.java
  Buycation/src/main/java/com/example/buycation/common/exception/ErrorCode.java
  Buycation/src/main/java/com/example/buycation/mail/service/EmailService.java
  Buycation/src/main/java/com/example/buycation/members/member/mapper/MemberMapper.java
  Buycation/src/main/java/com/example/buycation/members/member/service/MemberService.java
  Buycation/src/main/java/com/example/buycation/members/profile/service/ProfileService.java
  Buycation/src/main/java/com/example/buycation/participant/repository/ApplicationRepository.java
  Buycation/src/main/java/com/example/buycation/participant/repository/ParticipantRepository.java
  Buycation/src/main/java/com/example/buycation/participant/service/ParticipantService.java
  Buycation/src/main/java/com/example/buycation/posting/entity/Posting.java
  Buycation/src/main/java/com/example/buycation/posting/repository/PostingRepository.java
  Buycation/src/main/java/com/example/buycation/posting/service/PostingService.java
  Buycation/src/main/java/com/example/buycation/scheduler/Scheduler.java
Labels: feature, refactor

#62 ♻️ Refactor: cors 사이트 추가
  Buycation/src/main/java/com/example/buycation/security/config/WebSecurityConfig.java
Labels: refactor

#64 ✨ Feat: 카카오 로그인 API
  Buycation/src/main/java/com/example/buycation/members/member/controller/MemberController.java
  Buycation/src/main/java/com/example/buycation/members/member/dto/KakaoMemberInfoDto.java
  Buycation/src/main/java/com/example/buycation/members/member/entity/Member.java
  Buycation/src/main/java/com/example/buycation/members/member/mapper/MemberMapper.java
  Buycation/src/main/java/com/example/buycation/members/member/repository/MemberRepository.java
  Buycation/src/main/java/com/example/buycation/members/member/service/KakaoService.java
  Buycation/src/main/java/com/example/buycation/security/config/WebSecurityConfig.java
Labels: feature

#65 ♻️ Refactor: mysql dependency 추가 및 h2 테스트 코드로 변경
  Buycation/build.gradle
Labels: refactor

#67 ♻️ Refactor: 게시글상세, 프로필 조회 부분 수정
  Buycation/src/main/java/com/example/buycation/members/member/controller/MemberController.java
  Buycation/src/main/java/com/example/buycation/members/member/dto/LoginResponseDto.java
  Buycation/src/main/java/com/example/buycation/members/member/dto/MemberResponseDto.java
  Buycation/src/main/java/com/example/buycation/members/member/mapper/MemberMapper.java
  Buycation/src/main/java/com/example/buycation/members/member/service/KakaoService.java
  Buycation/src/main/java/com/example/buycation/members/member/service/MemberService.java
  Buycation/src/main/java/com/example/buycation/posting/controller/PostingController.java
  Buycation/src/main/java/com/example/buycation/posting/dto/PostingResponseDto.java
  Buycation/src/main/java/com/example/buycation/posting/mapper/PostingMapper.java
  Buycation/src/main/java/com/example/buycation/posting/service/PostingService.java
  Buycation/src/main/java/com/example/buycation/scheduler/Scheduler.java
  Buycation/src/main/java/com/example/buycation/security/config/WebSecurityConfig.java
Labels: refactor

#69 ✨ Feat: 이메일 인증 확인 API
  Buycation/src/main/java/com/example/buycation/common/MessageCode.java
  Buycation/src/main/java/com/example/buycation/common/exception/ErrorCode.java
  Buycation/src/main/java/com/example/buycation/mail/controller/EmailController.java
  Buycation/src/main/java/com/example/buycation/mail/entity/EmailCheck.java
  Buycation/src/main/java/com/example/buycation/mail/mapper/EmailCheckMapper.java
  Buycation/src/main/java/com/example/buycation/mail/repository/EmailCheckRepository.java
  Buycation/src/main/java/com/example/buycation/mail/service/EmailService.java
  Buycation/src/main/java/com/example/buycation/members/member/service/MemberService.java
  Buycation/src/main/java/com/example/buycation/security/config/WebSecurityConfig.java
Labels: feature

#71 ♻️ Refactor: 리뷰 했는지 체크용 boolean 추가
  Buycation/src/main/java/com/example/buycation/members/profile/dto/MemberReviewResponseDto.java
  Buycation/src/main/java/com/example/buycation/members/profile/mapper/ReviewMapper.java
  Buycation/src/main/java/com/example/buycation/members/profile/service/ProfileService.java
Labels: refactor

#76 ♻️ Refactor: CORS 주소 변경 및 추가
  Buycation/src/main/java/com/example/buycation/security/config/WebSecurityConfig.java
Labels: refactor

#78 ♻️ Refactor: 게시글 지원자 평균점수 노출 추가
  Buycation/src/main/java/com/example/buycation/participant/mapper/ApplicationMapper.java
Labels: refactor

#81 ♻️ Refactor: 닉네임 확인 API 리펙토링
  Buycation/src/main/java/com/example/buycation/members/member/controller/MemberController.java
  Buycation/src/main/java/com/example/buycation/members/member/service/MemberService.java
Labels: refactor

#72 Feat : 알림 기능 구현 v1
  Buycation/src/main/java/com/example/buycation/alarm/controller/AlarmController.java
  Buycation/src/main/java/com/example/buycation/alarm/dto/AlarmCountDto.java
  Buycation/src/main/java/com/example/buycation/alarm/dto/AlarmResponseDto.java
  Buycation/src/main/java/com/example/buycation/alarm/dto/RealtimeAlarmDto.java
  Buycation/src/main/java/com/example/buycation/alarm/entity/Alarm.java
  Buycation/src/main/java/com/example/buycation/alarm/entity/AlarmType.java
  Buycation/src/main/java/com/example/buycation/alarm/mapper/AlarmMapper.java
  Buycation/src/main/java/com/example/buycation/alarm/repository/AlarmRepository.java
  Buycation/src/main/java/com/example/buycation/alarm/repository/EmitterRepository.java
  Buycation/src/main/java/com/example/buycation/alarm/service/AlarmService.java
  Buycation/src/main/java/com/example/buycation/comment/service/CommentService.java
  Buycation/src/main/java/com/example/buycation/common/MessageCode.java
  Buycation/src/main/java/com/example/buycation/common/PageConfig/PageRequest.java
  Buycation/src/main/java/com/example/buycation/common/PageConfig/PageResponse.java
  Buycation/src/main/java/com/example/buycation/common/exception/ErrorCode.java
  Buycation/src/main/java/com/example/buycation/participant/service/ParticipantService.java
  Buycation/src/main/java/com/example/buycation/posting/repository/PostingRepository.java
  Buycation/src/main/java/com/example/buycation/scheduler/Scheduler.java
Labels: feature

#83 ♻️ Refactor: 신청자 리스트에 멤버 ID추가
  Buycation/src/main/java/com/example/buycation/participant/dto/ApplicationResponseDto.java
  Buycation/src/main/java/com/example/buycation/participant/mapper/ApplicationMapper.java
Labels: refactor

#85 ♻️ Refactor: 게시글 상세 조회한 사람이 참가자인지 체크
  Buycation/build.gradle
  Buycation/src/main/java/com/example/buycation/posting/dto/PostingResponseDto.java
  Buycation/src/main/java/com/example/buycation/posting/mapper/PostingMapper.java
  Buycation/src/main/java/com/example/buycation/posting/service/PostingService.java
Labels: refactor

#87 ♻️ Refactor : 알람 타입 수정, response 값 변경
  Buycation/src/main/java/com/example/buycation/alarm/entity/Alarm.java
  Buycation/src/main/java/com/example/buycation/alarm/entity/AlarmType.java
  Buycation/src/main/java/com/example/buycation/alarm/mapper/AlarmMapper.java
  Buycation/src/main/java/com/example/buycation/alarm/service/AlarmService.java
  Buycation/src/main/java/com/example/buycation/comment/service/CommentService.java
  Buycation/src/main/java/com/example/buycation/participant/service/ParticipantService.java
  Buycation/src/main/java/com/example/buycation/posting/repository/PostingRepository.java
  Buycation/src/main/java/com/example/buycation/scheduler/Scheduler.java
Labels: refactor

#88 ✨ Feat : 채팅 기능 구현 V1
  Buycation/build.gradle
  Buycation/src/main/java/com/example/buycation/common/MessageCode.java
  Buycation/src/main/java/com/example/buycation/common/exception/ErrorCode.java
  Buycation/src/main/java/com/example/buycation/posting/service/PostingService.java
  Buycation/src/main/java/com/example/buycation/talk/WebSocketConfig.java
  Buycation/src/main/java/com/example/buycation/talk/controller/ChatRoomController.java
  Buycation/src/main/java/com/example/buycation/talk/controller/TalkController.java
  Buycation/src/main/java/com/example/buycation/talk/dto/ChatRoomResponseDto.java
  Buycation/src/main/java/com/example/buycation/talk/dto/TalkRequestDto.java
  Buycation/src/main/java/com/example/buycation/talk/dto/TalkResponseDto.java
  Buycation/src/main/java/com/example/buycation/talk/entity/ChatRoom.java
  Buycation/src/main/java/com/example/buycation/talk/entity/Talk.java
  Buycation/src/main/java/com/example/buycation/talk/mapper/ChatRoomMapper.java
  Buycation/src/main/java/com/example/buycation/talk/mapper/TalkMapper.java
  Buycation/src/main/java/com/example/buycation/talk/repository/ChatRoomRepository.java
  Buycation/src/main/java/com/example/buycation/talk/repository/TalkRepository.java
  Buycation/src/main/java/com/example/buycation/talk/service/TalkService.java
Labels: feature

#89 ♻️ Refactor : 스케쥴러 임시 중지
  Buycation/src/main/java/com/example/buycation/scheduler/Scheduler.java
  Buycation/src/main/java/com/example/buycation/talk/entity/ChatRoom.java
  Buycation/src/main/java/com/example/buycation/talk/entity/Talk.java
Labels: refactor

#90 ♻️ Refactor : 첫 연결시 count 클라이언트 전송
  Buycation/src/main/java/com/example/buycation/alarm/controller/AlarmController.java
  Buycation/src/main/java/com/example/buycation/alarm/service/AlarmService.java
Labels: refactor

#91 Refactor : 첫 연결시 알림 갯수만 전송
  Buycation/src/main/java/com/example/buycation/alarm/controller/AlarmController.java
  Buycation/src/main/java/com/example/buycation/alarm/service/AlarmService.java
Labels: refactor

#92 Refactor : setAllowedOriginPatterns -> setAllowedOrigins
  Buycation/src/main/java/com/example/buycation/talk/WebSocketConfig.java
Labels: refactor

#94 ♻️ Refactor: 쿼리 DSL사용
  Buycation/build.gradle
  Buycation/src/main/java/com/example/buycation/common/config/QuerydslConfig.java
  Buycation/src/main/java/com/example/buycation/posting/repository/PostingRepository.java
  Buycation/src/main/java/com/example/buycation/posting/repository/PostingRepositoryCustom.java
  Buycation/src/main/java/com/example/buycation/posting/repository/PostingRepositoryImpl.java
  Buycation/src/main/java/com/example/buycation/posting/service/PostingService.java
Labels: refactor

#95 ♻️ Refactor : 웹소켓 관련 config 수정
  Buycation/src/main/java/com/example/buycation/alarm/controller/AlarmController.java
  Buycation/src/main/java/com/example/buycation/security/config/WebSecurityConfig.java
  Buycation/src/main/java/com/example/buycation/talk/WebSocketConfig.java
  Buycation/src/main/java/com/example/buycation/talk/controller/TalkController.java
Labels: refactor

#97 ♻️ Refactor: 권한 추가
  Buycation/src/main/java/com/example/buycation/security/config/WebSecurityConfig.java
Labels: refactor

#96 Refactor : 채팅방 조회시 image url 전송, 채팅방 입장 시 nickname 전송
  Buycation/src/main/java/com/example/buycation/talk/WebSocketConfig.java
  Buycation/src/main/java/com/example/buycation/talk/controller/ChatRoomController.java
  Buycation/src/main/java/com/example/buycation/talk/controller/TalkController.java
  Buycation/src/main/java/com/example/buycation/talk/dto/ChatRoomResponseDto.java
  Buycation/src/main/java/com/example/buycation/talk/dto/TalkEntryResponseDto.java
  Buycation/src/main/java/com/example/buycation/talk/entity/Talk.java
  Buycation/src/main/java/com/example/buycation/talk/mapper/ChatRoomMapper.java
  Buycation/src/main/java/com/example/buycation/talk/mapper/TalkMapper.java
  Buycation/src/main/java/com/example/buycation/talk/service/TalkService.java
Labels: refactor

#100 ♻️ Refactor : 알람 갯수만 반환
  Buycation/src/main/java/com/example/buycation/alarm/service/AlarmService.java
Labels: refactor

#103 ♻️ Refactor: 내 참가 게시글 조회에서 내가 개설한 게시글 제외
  Buycation/src/main/java/com/example/buycation/members/profile/service/ProfileService.java
Labels: refactor

#101 ♻️ Refactor : 읽음, 삭제 처리시 알람 갯수 반환
  Buycation/src/main/java/com/example/buycation/alarm/controller/AlarmController.java
  Buycation/src/main/java/com/example/buycation/alarm/entity/Alarm.java
  Buycation/src/main/java/com/example/buycation/alarm/service/AlarmService.java
  Buycation/src/main/java/com/example/buycation/posting/service/PostingService.java
  Buycation/src/main/java/com/example/buycation/talk/repository/ChatRoomRepository.java
  Buycation/src/main/java/com/example/buycation/talk/service/TalkService.java
Labels: refactor

#107 ♻️ Refactor: 댓글 권한 조건 체크 추가
  Buycation/src/main/java/com/example/buycation/comment/dto/CommentResponseDto.java
  Buycation/src/main/java/com/example/buycation/comment/mapper/CommentMapper.java
  Buycation/src/main/java/com/example/buycation/posting/service/PostingService.java
Labels: refactor

#109 fix : async 위치 변경
  Buycation/src/main/java/com/example/buycation/BuycationApplication.java
  Buycation/src/main/java/com/example/buycation/alarm/entity/AlarmType.java
  Buycation/src/main/java/com/example/buycation/alarm/service/AlarmService.java
  Buycation/src/main/java/com/example/buycation/common/config/AsyncConfig.java
  Buycation/src/main/java/com/example/buycation/common/config/RestTemplateConfig.java
  Buycation/src/main/java/com/example/buycation/common/exception/GlobalExceptionHandler.java
  Buycation/src/main/java/com/example/buycation/posting/service/PostingService.java
  Buycation/src/main/java/com/example/buycation/scheduler/Scheduler.java
  Buycation/src/main/java/com/example/buycation/talk/repository/ChatRoomRepository.java
  Buycation/src/main/java/com/example/buycation/talk/repository/TalkRepository.java
Labels: refactor
